version: "3.3"

services:
  front:
    build:
      context: ./front
    volumes:
      front_build:/dist/
  working_dir: /app

  back:
    build:
      context: ./back
    volumes:  
      ./back/prompts.sqlite:/app/prompts.sqlite
      ./front_build:./back/public
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 8080:8080
    depends_on:
      front

volumes:
  front_build: