version: "3.3"

services:
  front:
    build:
      context: ./front
    volumes:
      - front_build:/app/dist/
    working_dir: /app
  back:
    build:
      context: ./back
    volumes:
      - ./back/prompts.sqlite:/app/prompts.sqlite
      - front_build:/app/public/
    environment:
      NODE_ENV: production
    restart: always
    ports:
      - 8080:8080
    working_dir: /app
    depends_on: [ front ]

volumes:
  front_build: